baseURL = "https://nombi.info/"
languageCode = "ja"
defaultContentLanguage = "ja"
title = "NOMBIRIdoryoku"
theme = "hermit"

pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true
rssLimit = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
canonifyurls = true

[author]
  name = "siubiang"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  homeSubtitle = "Electronic work notes, small trip photos, etc."

  bgImg = "/img/posts/camera/summer-fes-3.jpg"
  gitUrl = "https://github.com/siubiang/blog/commits/"

  justifyContent = false
  relatedPosts = false
  code_copy_button = false

  # [[params.social]]
  #   name = "twitter"
  #   url = "https://twitter.com/siubiang"

  # [[params.social]]
  #   name = "instagram"
  #   url = "https://instagram.com/siubiang"

  # [[params.social]]
  #   name = "github"
  #   url = "https://github.com/siubiang"

[menu]

  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20

  [[menu.main]]
    name = "Contact"
    url = "https://profcard.info/u/vp61dkf6nMdMf1urIV0w1MqmX273"

  # [[menu.main]]
  #   name = "Links"
  #   url = "links/"
  #   weight = 30
